package hospitalmanagement;

//import java.sql.Statement;
//import java.sql.Connection;
//import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ADDDOCTOR.java
 *
 * Created on Jan 20, 2017, 9:22:07 PM
 */

/**
 *
 * @author win7
 */
public class ADDDOCTOR extends javax.swing.JFrame {

    /** Creates new form ADDDOCTOR */
    public ADDDOCTOR() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26));
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("                      ADD DOCTOR");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("PREFIX");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 80, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel3.setText("FIRST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 160, 94, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel4.setText("LAST NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 86, 19);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SPECIALISATION");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 80, 132, 19);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" CONTACT NUMBER");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 240, 150, 19);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel7.setText("GENDER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 280, 63, 19);

        jComboBox1.setFont(new java.awt.Font("Bell MT", 1, 13));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs.", "Sh.", "Smt." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 70, 60, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jTextField1.setToolTipText("DOCTOR_ID SHOULD BE OF 6 CHARACTERS  \nFIRST 3 CHARACTERS: SPECIALISATION  \nLAST 3 CHARACTERS: ID NUMBER");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 120, 110, 22);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 160, 110, 22);

        jList1.setFont(new java.awt.Font("Arial", 0, 14));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cardiologist", "Neurologist", "Gynaecologist", "Paediatrician", "Physician", "Surgeon", "Orthopedist", "Pschychiatrist", "Dermatologist", "Dentist", "ENT Specialist", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(395, 80, 100, 260);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 200, 110, 22);

        jButton1.setFont(new java.awt.Font("Papyrus", 1, 12));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 350, 90, 30);

        jButton2.setFont(new java.awt.Font("Papyrus", 1, 12));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 350, 100, 30);

        jButton3.setFont(new java.awt.Font("Papyrus", 1, 12));
        jButton3.setText(" EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 350, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("DOC_ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 120, 61, 19);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 240, 110, 22);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton1.setText(" MALE");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(160, 280, 80, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton2.setText("FEMALE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(280, 280, 80, 30);

        jButton4.setFont(new java.awt.Font("Papyrus", 1, 12));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 350, 90, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/screen-shot-2016-08-24-at-11-01-59-am.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
EXIT obj18= new EXIT();
obj18.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try
       {
        Class.forName("java.sql.DriverManager");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/HOSPITAL","root","12345");
        Statement stmt=con.createStatement();
        String prf,docid,fname,lname,gender = null,specia = null;
        int contact,pr,spec;
        pr=jComboBox1.getSelectedIndex();
        if(pr==0)
        {
            prf="Mr.";
        }
        else if(pr==1)
        {
            prf="Mrs.";
        }
        else if(pr==2)
        {
            prf="Sh.";
        }
        else if(pr==3)
        {
            prf="Smt.";
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Please select the approproate prefix");
        }
        docid=jTextField1.getText();
        fname=jTextField2.getText();
        lname=jTextField3.getText();
        if (jRadioButton1.isSelected()==true)
        {
            gender="MALE";
        }
        else if (jRadioButton2.isSelected()==true)
        {
            gender="FEMALE";
        }
        else
        {
         JOptionPane.showMessageDialog(this,"Please select the Gender");
        }
        contact=Integer.parseInt(jTextField4.getText());
        spec=jList1.getSelectedIndex();
        if (spec==0)
        {
            specia="CARDIOLOGIST";
        }
        else if (spec==1)
        {
            specia="NEUROLOGIST";
        }
        else if (spec==2)
        {
            specia="GYNAECOLOGIST";
        }
        else if (spec==3)
        {
            specia="PAEDIATRICIAN";
        }
        else if (spec==4)
        {
            specia="PHYSICIAN";
        }
        else if (spec==5)
        {
            specia="SURGEON";
        }
        else if (spec==6)
        {
            specia="ORTHOPEDIST";
        }
        else if (spec==7)
        {
            specia="PSCHYCHIATRIST";
        }
        else if (spec==8)
        {
            specia="DERMATOLOGIST";
        }
        else if (spec==9)
        {
            specia="DENTIST";
        }
        else if (spec==10)
        {
            specia="ENT SPECIALIST";
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Select the Specialisation of the Doctor");
        }

String query="Insert into Doctor values ('"+docid+"','"+fname+"','"+lname+"','"+contact+"','"+gender+"','"+specia+"');" ;
stmt.execute(query);
JOptionPane.showMessageDialog(this,"NEW RECORD OF DOCTOR INSERTED");

       }
catch (Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage()); 
}
    
// TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
DOCTORS obj17= new DOCTORS();
obj17.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDDOCTOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
