package hospitalmanagement;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ADDPATIENT.java
 *
 * Created on Jan 20, 2017, 9:13:37 PM
 */

/**
 *
 * @author win7
 */
public class ADDPATIENT extends javax.swing.JFrame {

    /** Creates new form ADDPATIENT */
    public ADDPATIENT() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 102, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26));
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("                         ADD PATIENT");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIRST NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 94, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LAST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 86, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE OF BIRTH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 270, 116, 19);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Cambria Math", 1, 13));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("MALE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(170, 310, 70, 25);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Cambria Math", 1, 13));
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("FEMALE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(270, 310, 90, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENDER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 310, 63, 19);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PREFIX");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 70, 19);

        jComboBox1.setFont(new java.awt.Font("Batang", 1, 12));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs.", "Ms.", "Sh.", "Smt." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 70, 60, 21);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONTACT NUMBER");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 350, 142, 19);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 110, 130, 23);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField2.setToolTipText("FILL IN CAPITALS");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 150, 130, 23);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField3.setToolTipText("FILL IN CAPITALS");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 190, 130, 23);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField4.setToolTipText("FILL IN CAPITALS");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 230, 130, 23);

        jButton1.setFont(new java.awt.Font("Papyrus", 1, 12));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(437, 171, 90, 30);

        jButton2.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 220, 100, 30);

        jButton3.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 330, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CITY");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 230, 37, 19);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DISEASE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 70, 70, 20);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField5.setToolTipText("FORMAT:   YYYY-MM-DD");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(170, 270, 130, 23);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(200, 350, 130, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PAT_ID");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 110, 70, 19);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(400, 70, 140, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DOC_ID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 120, 70, 19);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField8.setToolTipText("DOCTOR_ID SHOULD BE OF 6 CHARACTERS  \nFIRST 3 CHARACTERS: SPECIALISATION  \nLAST 3 CHARACTERS: ID NUMBER");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(400, 120, 140, 23);

        jButton4.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 280, 90, 29);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/patii.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -20, 570, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
EXIT obj18= new EXIT();
obj18.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try
       {
        Class.forName("java.sql.DriverManager");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/HOSPITAL","root","12345");
        Statement stmt=con.createStatement();
        String prf,patid,fname,lname,city,dob,gender = null,disease,docid ;
        int contact,pr;
        pr=jComboBox1.getSelectedIndex();
        if(pr==0)
        {
            prf="Mr.";
        }
        else if(pr==1)
        {
            prf="Mrs.";
        }
        else if(pr==2)
        {
            prf="Ms.";
        }
        else if(pr==3)
        {
            prf="Sh.";
        }
        else if(pr==4)
        {
            prf="Smt.";
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Please select the approproate prefix");
        }
        patid=jTextField1.getText();
        fname=jTextField2.getText();
        lname=jTextField3.getText();
        city=jTextField4.getText();
        dob=jTextField5.getText();
         if (jRadioButton1.isSelected()==true)
        {
            gender="MALE";
        }
        else if (jRadioButton2.isSelected()==true)
        {
            gender="FEMALE";
        }
        else
        {
         JOptionPane.showMessageDialog(this,"Please select the Gender");
        }
        contact=Integer.parseInt(jTextField6.getText());
        disease=jTextField7.getText();
        docid=jTextField8.getText();
       

String query="Insert into Patient values ('"+patid+"','"+fname+"','"+lname+"','"+city+"','"+dob+"','"+gender+"','"+contact+"','"+disease+"','"+docid+"');" ;
stmt.execute(query);
JOptionPane.showMessageDialog(this,"NEW RECORD OF PATIENT INSERTED");

       }
catch (Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
    JOptionPane.showMessageDialog(this,"Your entered DOC_ID does not correspond to any of the Doctor's ID in the hospital" );
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
jTextField7.setText("");
jTextField8.setText("");
jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   PATIENTS obj16= new PATIENTS();
obj16.setVisible(true);
this.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDPATIENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
