/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SEARCHPAT.java
 *
 * Created on Jan 21, 2017, 4:11:59 PM
 */

package hospitalmanagement;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author win7
 */
public class SEARCHPAT extends javax.swing.JFrame {

    /** Creates new form SEARCHPAT */
    public SEARCHPAT() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(51, 0, 153));
        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 16));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                  SEARCH BY PAT_ID");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 30, 360, 40);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 20));
        jLabel1.setText("    SEARCH PATIENT RECORDS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 360, 40);

        jLabel3.setBackground(new java.awt.Color(51, 0, 153));
        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAT_ID");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 57, 17);

        jLabel4.setBackground(new java.awt.Color(51, 0, 153));
        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FIRST NAME");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 98, 17);

        jLabel5.setBackground(new java.awt.Color(51, 0, 153));
        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LAST NAME");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 160, 92, 17);

        jLabel6.setBackground(new java.awt.Color(51, 0, 153));
        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DISEASE");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 360, 70, 17);

        jLabel7.setBackground(new java.awt.Color(51, 0, 153));
        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CITY");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 200, 37, 17);

        jButton1.setFont(new java.awt.Font("Batang", 1, 14));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 90, 100, 30);

        jButton2.setFont(new java.awt.Font("Batang", 1, 14));
        jButton2.setText(" BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 230, 90, 30);

        jButton3.setFont(new java.awt.Font("Batang", 1, 14)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 350, 100, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField1.setToolTipText("FILL IN CAPITALS");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 80, 140, 22);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13));
        jTextField2.setToolTipText("FILL IN CAPITALS");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 120, 140, 22);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13));
        jTextField3.setToolTipText("FILL IN CAPITALS");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 160, 140, 22);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 200, 140, 22);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 13));
        jTextField5.setToolTipText("DOCTOR_ID SHOULD BE OF 6 CHARACTERS   \nFIRST 3 CHARACTERS: SPECIALISATION  \nLAST 3 CHARACTERS: ID NUMBER");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(170, 240, 140, 22);

        jLabel8.setBackground(new java.awt.Color(51, 0, 153));
        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("D.O.B");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 240, 54, 17);

        jLabel10.setBackground(new java.awt.Color(51, 0, 153));
        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GENDER");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 280, 80, 20);

        jLabel11.setBackground(new java.awt.Color(51, 0, 153));
        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONTACT");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 320, 80, 17);

        jLabel12.setBackground(new java.awt.Color(51, 0, 153));
        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DOC_ID");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 400, 70, 17);

        jTextField6.setEditable(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(170, 280, 140, 20);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 13));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(170, 320, 140, 22);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 13));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(170, 360, 140, 22);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 13));
        getContentPane().add(jTextField9);
        jTextField9.setBounds(170, 400, 140, 22);

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 14));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/mns.jpg"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 510, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
       {
        Class.forName("java.sql.DriverManager");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/HOSPITAL","root","12345");
        Statement stmt=con.createStatement();
        String patid;
        patid=jTextField1.getText();               
String query="Select FIRST_NAME, LAST_NAME, CITY, DOB, GENDER, CONTACT, DISEASE, DOCTOR_ID from PATIENT where PATIENT_ID='"+patid+"';" ;
stmt.execute(query);
ResultSet rs=stmt.executeQuery(query);
if (rs.next())
{
    String fname=rs.getString("FIRST_NAME");
    String lname=rs.getString("LAST_NAME");
    String city=rs.getString("CITY");
    String dob=rs.getString("DOB");
    String gender=rs.getString("GENDER");
    String contact=rs.getString("CONTACT");
    String disease=rs.getString("DISEASE");
    String docid=rs.getString("DOCTOR_ID");
    
    jTextField2.setText(fname);
    jTextField3.setText(lname);
    jTextField4.setText(city);
    jTextField5.setText(dob);
    jTextField6.setText(gender);
    jTextField7.setText(contact);
    jTextField8.setText(disease);
    jTextField9.setText(docid);

}


       }
catch (Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
    JOptionPane.showMessageDialog(this,"PATIENT ID NOT AVAILABLE");
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
EXIT obj18= new EXIT();
obj18.setVisible(true);
this.setVisible(false);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
PATIENTS obj3= new PATIENTS();
obj3.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCHPAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
