/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UPDATEPAT.java
 *
 * Created on Jan 21, 2017, 4:12:43 PM
 */

package hospitalmanagement;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author win7
 */
public class SEARCHDOC extends javax.swing.JFrame {

    /** Creates new form UPDATEPAT */
    public SEARCHDOC() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 16));
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("                   SEARCH BY DOC_ID");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 50, 320, 30);

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Cambria", 1, 15));
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("  DOC_ID");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 90, 70, 30);

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 15));
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("  FIRST NAME");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 100, 30);

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Cambria", 1, 15));
        jLabel4.setForeground(new java.awt.Color(51, 0, 102));
        jLabel4.setText("  LAST NAME");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 190, 100, 30);

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Cambria", 1, 15));
        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("  SPECIALISATION");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 340, 140, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 13));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 380, 110, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 13));
        jButton2.setText(" BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 380, 110, 40);

        jLabel6.setBackground(new java.awt.Color(0, 204, 255));
        jLabel6.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 20));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" SEARCH DOCTOR RECORDS");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 10, 430, 40);

        jButton3.setFont(new java.awt.Font("Arial", 1, 13));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 380, 110, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField1.setToolTipText("DOCTOR_ID SHOULD BE OF 6 CHARACTERS  \nFIRST 3 CHARACTERS: SPECIALISATION  \nLAST 3 CHARACTERS: ID NUMBER");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 90, 170, 23);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField2.setToolTipText("FILL IN CAPITALS");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 150, 170, 20);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField3.setToolTipText("FILL IN CAPITALS");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(250, 190, 170, 20);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField4.setToolTipText("FILL IN CAPITLALS   \nEg: CARDIOLOGIST\n       NEUROLOGIST");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(250, 240, 170, 20);

        jTable1.setBackground(new java.awt.Color(0, 0, 102));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CAR101"},
                {"CAR102"},
                {"CAR107"},
                {"DEN601"},
                {"DEN602"},
                {"DER801"},
                {"ENT501"},
                {"GYN301"},
                {"NEU701"},
                {"NEU702"},
                {"ORT401"},
                {"PAE201"},
                {"PAE202"},
                {"PHY901"},
                {"PSY001"},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "AVAILABLE DOCTOR ID's"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 0, 180, 430);

        jLabel8.setBackground(new java.awt.Color(255, 204, 204));
        jLabel8.setFont(new java.awt.Font("Cambria", 1, 15));
        jLabel8.setForeground(new java.awt.Color(51, 0, 102));
        jLabel8.setText("  CONTACT");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 240, 90, 30);

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Cambria", 1, 15));
        jLabel9.setForeground(new java.awt.Color(51, 0, 102));
        jLabel9.setText("  GENDER");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 290, 90, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(250, 290, 170, 20);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(250, 350, 170, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/sas.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 480, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
EXIT obj18= new EXIT();
obj18.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
       {
        Class.forName("java.sql.DriverManager");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/HOSPITAL","root","12345");
        Statement stmt=con.createStatement();
        String docid;
        docid=jTextField1.getText();
String query="Select FIRST_NAME, LAST_NAME, CONTACT, GENDER, SPECIALISATION from DOCTOR where DOCTOR_ID='"+docid+"';" ;
stmt.execute(query);
ResultSet rs=stmt.executeQuery(query);
if (rs.next())
{
    String fname=rs.getString("FIRST_NAME");
    String lname=rs.getString("LAST_NAME");
    String contact=rs.getString("CONTACT");
    String gender=rs.getString("GENDER");
    String specia=rs.getString("SPECIALISATION");

    jTextField2.setText(fname);
    jTextField3.setText(lname);
    jTextField4.setText(contact);
    jTextField5.setText(gender);
    jTextField6.setText(specia);

}
       }
catch (Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DOCTORS obj4= new DOCTORS();
obj4.setVisible(true);
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCHDOC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
