/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UPDATEPAT.java
 *
 * Created on Jan 21, 2017, 4:19:04 PM
 */

package hospitalmanagement;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author win7
 */
public class UPDATEPAT extends javax.swing.JFrame {

    /** Creates new form UPDATEPAT */
    public UPDATEPAT() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18));
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("                         UPDATE PATIENT RECORDS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 40);

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 16));
        jLabel2.setForeground(new java.awt.Color(102, 0, 204));
        jLabel2.setText("                                PLEASE ENTER PATIENT'S ID");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 40, 590, 40);

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15));
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("  PAT_ID");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 90, 90, 20);

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15));
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("  FIRST NAME");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 140, 120, 20);

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15));
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText(" LAST NAME");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 190, 110, 20);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15));
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("  CONTACT");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 240, 100, 20);

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15));
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("    CITY");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 290, 80, 20);

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15));
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("     DISEASE");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 340, 120, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField1.setToolTipText("FILL IN CAPITALS");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 90, 200, 20);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 140, 200, 20);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 190, 200, 20);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(220, 240, 200, 20);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 15));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 290, 200, 20);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 340, 200, 20);

        jButton1.setFont(new java.awt.Font("Felix Titling", 1, 15));
        jButton1.setForeground(new java.awt.Color(204, 0, 102));
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(453, 123, 110, 40);

        jButton2.setFont(new java.awt.Font("Felix Titling", 1, 15));
        jButton2.setForeground(new java.awt.Color(204, 0, 102));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(453, 203, 110, 40);

        jButton3.setFont(new java.awt.Font("Felix Titling", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 102));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(453, 353, 110, 40);

        jButton4.setFont(new java.awt.Font("Felix Titling", 1, 15));
        jButton4.setForeground(new java.awt.Color(204, 0, 102));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(453, 283, 110, 40);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(220, 390, 200, 20);

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15));
        jLabel10.setForeground(new java.awt.Color(0, 153, 51));
        jLabel10.setText("  GENDER");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 390, 90, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/updapat.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 60, 580, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
    Class.forName("java.sql.DriverManager");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/HOSPITAL","root","12345");
        Statement upStat=con.createStatement();
            int res=JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO UPDATE THE CURRENT RECORD ?");
            if(res==JOptionPane.YES_OPTION) {

                String patid=jTextField1.getText(),contact=jTextField4.getText(), city=jTextField5.getText();
                upStat.execute("update PATIENT set CONTACT = '"+contact+"',CITY = '"+city+"' where PATIENT_ID='"+patid+"'");

                JOptionPane.showMessageDialog(null, "RECORD IS UPDATED IN THE DATABASE");
                upStat.close();

                jTextField1.setText(null);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField4.setText(null);
                jTextField5.setText(null);
                jTextField6.setText(null);
                jTextField7.setText(null);

                    }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
EXIT obj18= new EXIT();
obj18.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
PATIENTS obj16= new PATIENTS();
obj16.setVisible(true);
this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
       {
        Class.forName("java.sql.DriverManager");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/HOSPITAL","root","12345");
        Statement stmt=con.createStatement();
        String patid;
        patid=jTextField1.getText();



String query="Select FIRST_NAME, LAST_NAME, CONTACT, CITY, DISEASE, GENDER  from PATIENT where PATIENT_ID='"+patid+"';" ;
stmt.execute(query);
ResultSet rs=stmt.executeQuery(query);
if (rs.next())
{
    String fname=rs.getString("FIRST_NAME");
    String lname=rs.getString("LAST_NAME");
    String contact=rs.getString("CONTACT");
    String city=rs.getString("CITY");
    String disease=rs.getString("DISEASE");
    String gender=rs.getString("GENDER");


    jTextField2.setText(fname);
    jTextField3.setText(lname);
    jTextField4.setText(contact);
    jTextField5.setText(city);
    jTextField6.setText(disease);
    jTextField7.setText(gender);


}


       }
catch (Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}
    disAllow();
    }

public void disAllow()
{
  jTextField2.setEditable(false);
  jTextField3.setEditable(false);
  jTextField4.setEditable(true);
  jTextField5.setEditable(true);
  jTextField6.setEditable(false);
  jTextField7.setEditable(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEPAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
