/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UPDATEDOC.java
 *
 * Created on Jan 21, 2017, 4:12:34 PM
 */

package hospitalmanagement;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author win7
 */
public class UPDATEDOC extends javax.swing.JFrame {


    /** Creates new form UPDATEDOC */
    public UPDATEDOC() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setState(1);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 16));
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("                                     UPDATE DOCTOR RECORDS");
        jLabel1.setMaximumSize(new java.awt.Dimension(380, 200));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 40);

        jLabel8.setBackground(new java.awt.Color(153, 153, 255));
        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 16));
        jLabel8.setText("                                       PLEASE ENTER DOCTOR'S ID");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-6, 30, 560, 50);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 15));
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("    DOC_ID");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 90, 110, 30);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 15));
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("  FIRST NAME");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 140, 110, 30);

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 15));
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("  LAST NAME");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 200, 110, 30);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 15));
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("    CONTACT");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 260, 110, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField1.setToolTipText("DOCTOR_ID SHOULD BE OF 6 CHARACTERS  \nFIRST 3 CHARACTERS: SPECIALISATION  \nLAST 3 CHARACTERS: ID NUMBER");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(320, 90, 190, 20);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(320, 140, 190, 20);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(320, 200, 190, 20);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(320, 260, 190, 20);

        jButton1.setFont(new java.awt.Font("Book Antiqua", 1, 15));
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 370, 90, 30);

        jButton2.setFont(new java.awt.Font("Book Antiqua", 1, 15));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 370, 100, 30);

        jButton3.setFont(new java.awt.Font("Book Antiqua", 1, 15)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 370, 80, 30);

        jButton4.setFont(new java.awt.Font("Book Antiqua", 1, 15));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 370, 90, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 15));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(320, 320, 190, 20);

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 15));
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("   SPECIALISATION");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 320, 150, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/UPDADOC.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 550, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
DOCTORS obj16= new DOCTORS();
obj16.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
    Class.forName("java.sql.DriverManager");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/HOSPITAL","root","12345");
        Statement upStat=con.createStatement();
            int res=JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO UPDATE THE CURRENT RECORD ?");
            if(res==JOptionPane.YES_OPTION) {

                String docid=jTextField1.getText(),contact=jTextField4.getText();
                upStat.execute("update DOCTOR set CONTACT = "+contact+" where DOCTOR_ID='"+docid+"'");

                JOptionPane.showMessageDialog(null, "RECORD IS UPDATED IN THE DATABASE");
                upStat.close();

                jTextField1.setText(null);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField4.setText(null);
                jTextField5.setText(null);
                
                    }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }




    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
       {
        Class.forName("java.sql.DriverManager");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/HOSPITAL","root","12345");
        Statement stmt=con.createStatement();
        String docid;
        docid=jTextField1.getText();



String query="Select FIRST_NAME, LAST_NAME, CONTACT, SPECIALISATION from DOCTOR where DOCTOR_ID='"+docid+"';" ;
stmt.execute(query);
ResultSet rs=stmt.executeQuery(query);
if (rs.next())
{
    String fname=rs.getString("FIRST_NAME");
    String lname=rs.getString("LAST_NAME");
    String contact=rs.getString("CONTACT");
    String specia=rs.getString("SPECIALISATION");

    jTextField2.setText(fname);
    jTextField3.setText(lname);
    jTextField4.setText(contact);
    jTextField5.setText(specia);

}


       }
catch (Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}
    disAllow();
    }

public void disAllow()
{
  jTextField2.setEditable(false);
  jTextField3.setEditable(false);
  jTextField5.setEditable(false);
  jTextField4.setEditable(true);

      // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
EXIT obj18= new EXIT();
obj18.setVisible(true);
this.setVisible(false);    // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEDOC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
